name: release

on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: Which number to bump
        options: 
        - major
        - minor
        - patch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: cache
        uses: actions/cache@v3
        with:
            path: ~/.cargo/bin/cargo-release
            key: ${{ runner.os }}-cargo-release
      - run: cargo install cargo-release
        if: steps.cache.outputs.cache-hit != 'true'
      - run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - run: cargo release ${{ github.event.inputs.level }} --execute
